name: Lint

on:
  push:
    branches:
      - 'main'
  issue_comment:

jobs:
  lint:
    if: ${{ github.event_name != 'issue_comment' || ( github.event.issue.pull_request && contains(github.event.comment.body '/support') }}

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew clean

      - name: Lint
        run: ./gradlew spotlessApply

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[bot] Lint'
